### PR TITLE
added missing state in getCustomUrl for config.getURL(url, state)

### PR DESCRIPTION
**Pull request by jeremym**
added missing state in getCustomUrl for config.getURL(url, state);  also, 'state' was declared in upper scope and causing IDE warnings.

### CODE REVIEW

**Comment by jeremym** [comment]
Hey @hamxabaig

Let me know if creating a PR is how you'd like to get code changes into your project.  I have another one in which a project I'm working with has an empty response body on 401s which causes your onRequestError marshaller to throw an error at res.json() with "Unexpected end of JSON input".

**Comment by hamxabaig** [comment]
@jeremym Thanks for the PR. Sorry I was travelling so didn't see it. I'll review it soon and let you know. If you find any bugs, please create an issue & if you know how to fix it any help would be great ☺️

**Comment by jeremym** [comment]
Cool cool.   Thanks for the response, @hamxabaig.  My PR really just passes 'state' in line 12 to fix the undefined I was seeing in the current release.

I just submitted another quick issue and could create more PRs for that and for the other one I mentioned.  I think I mentioned it? :-) -- `res.json();` blows chunks when the backend is configured to return an empty response on a 401 -- not sure if my quick fix was the best, but I instead did a res.text().  In the then() I check if response text is empty and if not execute a res.json() --- so it's a longer chain of promises than feels necessary, but it fixed my bug.

**Comment by hamxabaig** [comment]
@jeremym Cool, If you can submit a PR would be awesome.

**Pull request merged**
